UnitedLexCorp/SimpleTalk

css/core.css
js/objects/System.js
js/objects/parts/Button.js
js/objects/parts/Card.js
js/objects/parts/Part.js
js/objects/parts/editors/ButtonEditor.js
js/objects/tests/preload.js
js/objects/tests/test-editors-with-preload.js
js/objects/views/ButtonView.js
js/objects/views/FieldView.js
js/objects/views/Halo.js
js/objects/views/PartView.js
js/objects/views/drawing/ColorWheelWidget.js
js/objects/views/editors/ButtonEditorView.js

After some pain, a button editor. It does the basic things: 
Changes the name
Adjusts background and font colors (via our colorWheel)
Lists, adds, removes events
And lets you script
The editor is opened by pressing the "write/edit" icon, which previously opened the script/field editor. 
Instead of embedding all the widgets necessary to do editing (color, script) inside one editor view I decided that each would open it's own, absolutely positioned, widget. After some experimenting with both options, this was easier to style and scale, and in the end I prefer it overall. This way you can lay out the various sub-editor widgets as you see fit and we can just keep making more, adding  a button to open it to the main one:
I tried to [stick to …

Button editor

---

js/objects/System.js
js/objects/parts/Part.js
js/objects/tests/test-error-handling-with-preload.js
js/objects/utils/errorHandler.js
js/objects/utils/eventMessenger.js
js/objects/views/FieldView.js

This PR introduces a prototype [error handler](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-syntax-debug?expand=1#diff-ad019d33cd101d6adeceb9553b2dfeeef98a8a808209c536107b05d948ff9ca2) 
The only types of errors it handles at the moment are `GrammarMatchError` and the rest it sends to System. But we like this setup it's clear how to add more cases. 
In the `GrammarMatchError` message there is now a [bit more](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-syntax-debug?expand=1#diff-27807be337857d016752d52609f4312048ef006984f0d2e108676823ffe892f6R318) data coming from Ohm, which is then used by the error handler to mark up the script. 
All it does is add a `<<<` marker at the end of the guilty line and some additional information (if Ohm provides it). Moreover, it …

Daniel syntax debug

---

css/core.css
js/objects/views/FieldView.js
js/objects/views/WindowView.js

Resizing on windows was broken. 
st-window -> st-stack -> st-card resizing was not working properly
allowing children of st-window.st-stack.st-card to grow and fit their parent
fixing various st-field related height and overflow issues
adding an active pseudo-class to boost z-index on selected elements
Our css is a little hacky, but this is a more global issues since we don't really know what we want.
Some things to consider:
* at the moment when we resize window we resize the [window-internal stack](https://github.com/UnitedLexCorp/SimpleTalk/blob/7e47e27a9e1158ffd9e286a9b9a722fe9b1c1691/js/objects/views/WindowView.js#L241) and then have the window parent adjust. Do we want to do this? or do we want to resize the window and have its children flex grow into it. 
* we should have a more …

fixing various css issues

---

js/objects/tests/test-if-then-with-preload.js
js/objects/tests/test-repeat-with-preload.js
js/objects/tests/test-variable-scripts-with-preload.js
js/ohm/interpreter-semantics.js
js/ohm/simpletalk.ohm
js/ohm/tests/test-conditional-grammar.js
js/ohm/tests/test-if-then-else-grammar.js
js/ohm/tests/test-repeat-grammar.js

This PR implements the basic looping constructs, called `repeat`. It is based almost entirely upon the HT specification.
Looping is conducted inside of what we call "repeat blocks." Each of these blocks begins with the keyword `repeat` (along with more specific forms), some lines of statements to execute each run of the loop, and the `end repeat` to finish the block. There are several types of repeat blocks one can use:
This construct repeats a loop for some number of times.
```simpletalk
repeat for 5 times
beep
end repeat
```
This construct will repeat the loop until some condition evaluates to true:
```simpletalk
put 5 into myCounter
repeat until myCounter <= 0
beep
put (myCounter - 2) into myCounter
end repeat
```
This construct is the opposite of the `until` variant, and will repeat …

Repeat (looping)

---

js/objects/System.js
js/objects/parts/Part.js
js/objects/tests/test-error-handling-with-preload.js
js/objects/tests/test-parts-with-preload.js
js/objects/tests/test-system-script-editor-with-preload.js
js/objects/utils/errorHandler.js
js/objects/views/FieldView.js

This PR introduces runtime error handling, in particular the `MessageNotUnderstood` command type error as seen [here](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-runtime-errors?expand=1#diff-ad019d33cd101d6adeceb9553b2dfeeef98a8a808209c536107b05d948ff9ca2R52). With PR #99 we now have both grammar (scripting) and runtime error handling. In addition, it introduces the [command registry](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-runtime-errors?expand=1#diff-efd61be9944474fec7ba0b89d7a931fedae606964b569ff27b2766271c5244b9R90) which gathers information about commands available to the part and up the stack (keeping track of where the command is handled and whether it overrides one from above).  The registry addresses this issue #101 
A picture is best to explain …

Runtime errors

---

js/objects/ExecutionContext.js
js/objects/parts/Button.js
js/objects/parts/Drawing.js
js/objects/views/drawing/DrawingView.js
js/ohm/interpreter-semantics.js

This PR does two things:
1. Gives us the ability to execute basic drawing commands on the Drawing part via scripting/built-in command handlers;
2. Fixes an important issue regarding ExecutionContext, where old contexts were not being restored and variables were being overwritten.
See the explanation in [this commit](https://github.com/UnitedLexCorp/SimpleTalk/commit/cd15af59d135e22af1f17a7854028d236859f918)
We currently support the following commands: `beginDraw`, `finishDraw`, `lineTo`, `moveTo`, `stroke`. See the example script below.
What other drawing operations should we support? Should values like line width, color, fillstyle, etc be set as properties on the model, or should they be set via commands? The latter would work, since the model activates its own canvas context after …

Scripted Drawing and Context Fixes

---

css/core.css
js/objects/parts/Button.js
js/objects/parts/Card.js
js/objects/parts/Container.js
js/objects/parts/Drawing.js
js/objects/parts/Field.js
js/objects/parts/Image.js
js/objects/parts/Part.js
js/objects/parts/Window.js
js/objects/properties/LayoutProperties.js
js/objects/properties/PartProperties.js
js/objects/tests/test-editors-with-preload.js
js/objects/tests/test-styling-with-preload.js
js/objects/utils/styler.js
js/objects/views/ButtonView.js
js/objects/views/CardView.js
js/objects/views/ContainerView.js
js/objects/views/FieldView.js
js/objects/views/Halo.js
js/objects/views/PartView.js
js/objects/views/StackView.js
js/objects/views/WindowView.js
js/objects/views/WorldView.js
js/objects/views/editors/ButtonEditorView.js
js/ohm/simpletalk.ohm

Here we refactor and cleanup the css, which includes the [core.css](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-css-refactoring?expand=1#diff-c753a1396e7b4b55330c513675b157cc4aed6cb4508b6f00831bf44d20183c4d) as well as all the shadow styling that happens in custom web components themselves. The idea was to set as much of the general styling in the [core.css](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-css-refactoring?expand=1#diff-c753a1396e7b4b55330c513675b157cc4aed6cb4508b6f00831bf44d20183c4d) file,  insisting that the shadow element sub-DOM would respond to this top level setting (to would allow for more explicitness and work well with controlling styles programmatically). This was largely successful, outside of `st-drawing` which interfaces with the …

css refactoring

---

js/objects/System.js
js/ohm/interpreter-semantics.js
js/ohm/simpletalk.ohm
js/ohm/tests/test-tell-grammar.js

The tell sends a command message to some other specified part. This is
a way of sending messages outside of the message delegation chain.
It takes the form of:
`tell <ObjectSpecifier> to <Command>`
For example:
```simpletalk
tell first image of this card to loadFromUrl "http://some-image-source"
```
Note that the message is a deferred one. The tell command's first
argument is the id of the part that should execute it, and the second
argument is a correctly formatted command message object. The target,
once found, will simply send that second argument to itself. This
means that the part invoking the 'tell' command originally *will not
appear in the message's senders list*. This is what we'd expect, since
it is essentially "spoofing" the message send.

Adding built in 'tell' command

---

js/objects/tests/test-string-concatenation-with-preload.js
js/ohm/interpreter-semantics.js
js/ohm/simpletalk.ohm
js/ohm/tests/test-string-grammar.js

This PR (finally!) implements a first pass at string concatenation.
You can concatenate any two Expressions using the `&` symbol. The expressions on either side of the symbol **will be coerced into strings** and concatenated into a resulting string. This has the advantage of easily turning numerical values into strings that can be displayed.
Because any variable is also a Factor, and any Factor is an Expression, you can concatenate variables as well. These will also be coerced into strings first.
```simpletalk
on click
answer "Hello, " & "world!"
end click
```
```simpletalk
on click
put "world!" into mySuffix
answer "Hello, " & mySuffix
end click
```
```simpletalk
on click
answer "You clicked " & 2.4 & " times on average"
end click
```
```simpletalk
on click
put 4 into numCycles
answer …
```

String Concatenation

---

images/SimpletalkDistortedText.svg
js/objects/parts/Image.js

This PR implements a built-in command that allows the Image part to load data from a local file on the user's filesystem.
It's rather simple: when the Image part receives the `loadImageFromFile` message, it will create an invisible file input element in the DOM, click it, and update the Image Part's `imageData` part property to be the data from the file.
Note also that the Image Part's `src` property and `mimeType` will also be updated. We assume that an Image Part whose `src` is null is a locally-loaded image. This is for future serialization purposes -- we want to make sure that when a page loads, we *don't* attempt to load from the set `src`, but rather simply display the cached `imageData` serialization.
Because this involves user interaction, we really need to test it ourselves. Here …

Image from Local File

---

css/core.css
js/objects/parts/Button.js
js/objects/parts/Container.js
js/objects/parts/Drawing.js
js/objects/parts/Field.js
js/objects/parts/Image.js
js/objects/parts/Window.js
js/objects/tests/test-styling-with-preload.js
js/objects/utils/styler.js
js/objects/views/FieldView.js
js/objects/views/drawing/ColorPickerTool.js
js/objects/views/drawing/ColorWheelWidget.js
js/objects/views/drawing/DrawingView.js
js/objects/views/editors/ButtonEditorView.js

A simple setup for "transparent" and "visible" part properties. The properties and styler are fine and trivial to set up. 
I added these to the color-wheel (there is an [option](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-transparent?expand=1#diff-2433c8a1dcdb9e45dfd097ee0a4178a4d44f6a2f3f5f121f6f61b97644b962e9R166) to not include them). Since the color-wheel was set up to send custom events on color select, b/c it is not aware of its target, I decided to stick to the same framework. I don't think it's very good though and forces a lot more code than necessary. For example you need to write event handlers for each part-view that has a color wheel acting on it. 
I think better would be to create editors for each part that are fully aware of their target, like button editors, …

transparent

---

js/objects/parts/Part.js
js/objects/properties/PartProperties.js
js/objects/tests/test-view-prop-handling-preload.js
js/objects/views/PartView.js
js/ohm/simpletalk.ohm
js/ohm/tests/test-grammar.js

After a view receives a `propertyChanged` type message it will [send](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-command-propChanged?expand=1#diff-f8a644f39713f7d56b51b944769a8733fceb081884704c2a73b93c232b554560R150) a type `command` `propertyChanged` message to its model/part. This message is set not to delegate, which is a new option for messages handled [here](https://github.com/UnitedLexCorp/SimpleTalk/compare/daniel-command-propChanged?expand=1#diff-efd61be9944474fec7ba0b89d7a931fedae606964b569ff27b2766271c5244b9R387). 
Note: the `propertyChanged` command is sent **regardless** of whether the view subscribes to the property being changed. This is necessary because a given property might (dynamically) alter another property which the view subscribes to. Our StyleProps …

command prop changed

---

js/objects/System.js
js/objects/examples/bootstrap.html
js/objects/parts/Part.js
js/objects/parts/Window.js
js/objects/parts/WorldStack.js
js/objects/tests/preload.js
js/objects/tests/test-serialization-with-preload.js
js/objects/utils/idMaker.js
js/objects/views/ButtonView.js
js/objects/views/WorldView.js

This PR ensures that IDs are preserved and correctly loaded again across the serialization / deserialization lifecycle.
The previous issue was that some Parts, like the Stack, will create an initial Card as a subpart of themselves when constructed. This was throwing off our `idMaker` module, which for the moment is a dumb incrementer. 
The strategy employed here does the following:
1. Ensures that each Part knows how to deserialize itself, via a class method `fromSerialized`. This method should return a Part instance. Note that WorldStack and Window have special behavior for this method. Otherwise all other parts use the Part.js base implementation
2. Resets the `idMaker`'s count to be the maximum ID value once all Parts have been deserialized. This ensures that the "next" created Part by …

Serialization IDs

---

js/objects/tests/test-property-value-with-preload.js
js/ohm/interpreter-semantics.js
js/ohm/simpletalk.ohm
js/ohm/tests/test-property-value-grammar.js

This PR implements a first pass at allowing users to read and use Part Property values in scripts. This ability did not exist until now -- we could set property values, but not "read" them.
The grammar change is simple enough. The pattern is, generally, `the "<propName>" of <ObjectSpecifier>`. There is an alternate form where you can drop the `of <ObjectSpecifier>` portion and the Part will implicitly be the one invoking the script handler.
Note also that this new rule `PropertyValue`, is also a `Factor`, meaning it can be used in Expressions or any other rule that can accept expressions.
```simpletalk
on click
-- Answer the "name" property value of the button
answer the "name"
-- Also answer the "name" property value of the button,
-- but using a specifier
answer the "name" of this …
```

Reading Property Values in Scripts

---

js/objects/System.js
js/objects/parts/Field.js

There was an issue when saving a snapshot where XMLSerializer was
escaping HTML characters inside of JSON inside of a script tag.
Instead, we no longer use XMLSerializer and simply get the outerHTML
of the document's documentElement.
Additionally, we are no longer serializing the `textContent` property for Fields at all. See the override definition of `serialize()` in the `Field.js` Part class.

Fixing Field Serialization Issue

---

js/objects/views/PartView.js

-- What
In order to properly manage layouts and ensure that parts inside of an
owner with a list layout cannot me moved (when halo open), we use the
PartView >> #wantsHaloMove getter. This was previously checking for
the value of the owner model's layout property. However, Stacks
don't (for the moment) have layout properties, and thus attempting to
move a Part that was in a Stack triggered a property lookup error.
This has been resolved.

[BUGFIX] Parts on a Stack can now be moved when halo open

---

js/objects/System.js
js/objects/parts/Card.js
js/objects/parts/Stack.js
js/objects/parts/WorldStack.js
js/objects/tests/test-stack-navigation-with-preload.js
js/objects/views/CardView.js
js/objects/views/StackView.js
js/objects/views/WorldView.js

This PR is a fix for Issue #138, which deals with moving the 'current' property from Cards and Stacks up a level to the owner parts that manage this state, namely WorldStack and Stack.
The property is still named `current`, but has been moved up a level and now has a different meaning. It refers to the 0-indexed based location of the current item (a card, in the case of Stack or a stack in the case of World) in a filtered list of like-kind items. This was done in anticipation of compatibility with forthcoming `number` properties as well as simplifying the navigation methods.
We also had to make minor updates to some System functions and tests, but everything seems to be working.
Still each of us should test this live (testing card navigation etc) just to be sure.
#138

Issue 138: Currentness

---

js/objects/System.js
js/objects/parts/Part.js
js/objects/tests/test-clipboard-with-preload.js
js/objects/tests/test-system-model-add-remove-preload.js
js/objects/utils/clipboard.js
js/objects/views/ButtonView.js
js/objects/views/FieldView.js
js/objects/views/Halo.js
js/objects/views/PartView.js

This PR implements a first pass at Part copy and paste functionality. To accomplish this we introduce a new `STClipboard` object on the System that handles most of the complexity. Note that it is completely separate from the OS/Browser based clipboard and copy/paste actions (see below).
`STClipboard` represents a kind of SimpleTalk-only clipboard that can be invoked directly by the System. There are two primary methods intended to be the main API:
* `copyPart(aPartObject)` -- This serializes the passed Part into a special store, along with a custom mimeType of `simpletalk/json'`. Note that these serializations, unlike the saveHTML ones, _not_ flattened.
* `pasteContentsInto(aPartObject)` -- This method will attempt to deserialize an object from the clipboard and, if available and if the …

Copy and Paste (STClipboard v1)

---

js/objects/System.js
js/objects/parts/Drawing.js
js/objects/parts/Part.js
js/objects/views/drawing/DrawingView.js

This PR represents a few bugfixes for issues we discovered after the most recent merge. They include:
* Changes to how `getCurrentCardModel` etc are implemented and used (this affects some aspects of navigation);
* Ensuring that `add <partName>` without an object specifier can deal with ambiguity appropriately (using message delegation)
* Fixing the issue identified in Issue #159 
There are still some stack navigation tests failing for reasons I have not yet been able to determine, but that situation already exists on master.
#159

Postmerge Fixes

---

css/core.css
js/objects/System.js
js/objects/parts/Image.js
js/objects/parts/Stack.js
js/objects/properties/PartProperties.js
js/objects/tests/test-subparts.js
js/objects/utils/clipboard.js
js/objects/views/StackView.js
js/ohm/simpletalk.ohm
js/ohm/tests/test-grammar.js
package.json

This PR adds an `importWorld` command which all you to import stacks from either local filepaths or urls. The command takes a source string argument but if you don't provide it a dialogue will come up asking for a location. (For example, you can import bootstrap.html into bootstrap.html, either by giving the browser url or the path to the file, while inside bootstrap url). 
Moreover, since we have not worked with multiple stacks much a number of bugs were uncovered. Namely the `visibility` css property is not inherited so using it as a way to hide/show stacks was actually making no difference. This has been replaced by using the `display` property. 
System de-serialization was updated to reflect the work in the currentness PR #140, which made things cleaner and fixed some minor bugs. …

Import world

---

js/objects/System.js
js/objects/tests/test-system-with-preload.js

This PR adds a `globalInterrupt` command handler to the System. At the moment it cycles through all parts and set `stepping` to false in those which are stepping. The handler can be called either via message or by keydown ctrl-c combo. 
Tests were added. 
This PR closes issue #129

adding a global Interrupt

---

css/core.css
images/card-icon.svg
images/stack-icon.svg
js/objects/System.js
js/objects/parts/Part.js
js/objects/tests/preload.js
js/objects/tests/test-stack-navigation-with-preload.js
js/objects/views/FieldView.js
js/objects/views/PartView.js
js/objects/views/WorldView.js
js/objects/views/navigator/CardRow.js
js/objects/views/navigator/Navigator.js
js/objects/views/navigator/StackRow.js
js/objects/views/navigator/WrappedView.js

This PR implements a new basic System accessible webcomponent called `Navigator`. It provides an interactive view of all available stacks and cards on those stacks. 
We introduce the concept of "lensing," whereby a given PartView subclass has `part-id` replaced with `lens-part-id` but maintains the same id mapping. This allows us to recreate a tree of subviews that will be the same as the main Part they are "mapping," while not being the primary views. This also allows the "lensed" views to be bound to and react to the same model as their primaries.
In short, this is how the miniature Card and Stack views work inside the Navigator -- they contain nested "lensed" views that are still able to react to changes on the common model all the way down.
Navigator is not a new kind of Part, but it …

Navigator v1

---

js/objects/System.js
js/objects/parts/Part.js
js/objects/parts/Window.js
js/objects/parts/WorldStack.js
js/objects/tests/test-clipboard-with-preload.js
js/objects/tests/test-lifecycle-scripting-with-preload.js
js/objects/tests/test-serialization-with-preload.js
js/objects/utils/clipboard.js
js/objects/utils/serialization.js
js/objects/views/WorldView.js

This PR introduces new serialization classes separate from the System. It should  make understanding and debugging the serialization/deserialization process a bit better. It has also improved the performance of operations like `importWorld` dramatically.
We introduce [two new classes](https://github.com/UnitedLexCorp/SimpleTalk/blob/eric-modular-serialization/js/objects/utils/serialization.js): `STDeserializer` and `STSerializer`. Each take a System as their constructor's sole argument. They are designed to be used not only by System, but by any tool that requires serializing/deseralizing. For example, the clipboard has been updated to exclusively use these classes in copying and pasting Part information.
`STDeserializer.deserialize()` is **now an asychronous operation**. Here we are …

Serialization v2

---

js/objects/utils/handInterface.js

A bug as introduced in commit 6c09655e which introduced hand smoothing computations. I have no clue how this happened since I had previously tested this and used it. The only explanation is that I screwed up a merge or something and didn't realize that my change messed things up and then just stopped looking at the hand stuff for a while.
Anyway the fix is tiny and trivial so there's that...

[bugfix] Fix hand position smoothing computation

---

css/core.css
js/objects/System.js
js/objects/tests/test-audio-with-preload.js
js/objects/tests/test-button-system-commands-with-preload.js
js/objects/tests/test-system-with-preload.js
js/objects/tests/test-views-lifecycle-with-preload.js
js/objects/utils/clipboard.js
js/objects/views/FieldView.js
js/objects/views/WorldView.js
js/objects/views/navigator/CardRow.js
js/objects/views/navigator/Navigator.js
js/objects/views/navigator/StackRow.js
js/objects/views/navigator/WrappedView.js

This PR fixes display and logic bugginess in the Navigator.
There were several cascading problems, partially identified in #179  and #180, that were causing Navigator to completely bug-out and at times freeze the whole system.
There were a few things going on. First, flipping back and forth quickly between two Stacks with the Nav open could lead to display bugs. This is because the CardRow for each Stack was being composed and re-rendered on the fly each time, meaning a whole tree of elements was being copied, inserted, and having its model set (recursively) each time we switched between stacks.
The "layout pushes up" issue was a fairly arcane one. It only applied to `FieldView` and no other parts. It turns out that `FieldView` sets its element focus when it is attached to the DOM. …

Navigator Fixes and Revisions

---

js/objects/views/WindowView.js

This PR updates how `st-window` resizes. Before it was directly setting the width/height inline styles on its stack subpart, which was an early solution before we had style properties. The issue is that this prevented window state from being property serialized and from being updated/seen in the navigator (I.e. adjusting the size of the window would not be reflected in the nav). 
Now window updates its width/height props. 
**NOTE**  Updating the window size and then opening the navigator throws the following error: 
This might all be fixed with #183 or this might be due to the version of the serialization for the example files coming from #184 
regardless we should be weary and potentially merge this in before #183 or rebase the latter on top of it to test.

Window resize

---

js/objects/System.js
js/objects/views/navigator/WrappedView.js

This PR implements a couple of quick fixes to issues that were breaking serialization/deserialization.
The first was that the devtool was interfering with deserialized Drawings, because the Drawing part sends messages when its image part property is set and devtool was expecting a world to already exist when intercepting all messages.
The second is that the Nav had certain expectations of lensed PartViews that was not always consistent.
Both of these have been fixed with easy changes. See the commit comments for more information.
Try serializing anything with drawings in it and re-opening. Additionally, try importing stacks that have Drawings, like mandate.
#173
#177

Serialization / Drawing Fixes

---

js/ohm/simpletalk.ohm

please use tabs not spaces in grammar (I use default tab 2 spaces, but it doesn't matter how things display locally if you match the current setup)
now the grammar file is spaced out consistently everywhere (web, raw, ohm editor etc)

cleanup of grammar tabs vs spaces

---

css/core.css
js/objects/views/Halo.js
js/objects/views/PartView.js

This PR implements a new Halo button and mode of interaction that allows us to visually and interactively set the target of one part to be another part.
The Halo now has a "target" button. Click this will put the system into "target mode," as indicated by the crosshair cursor. Hovering over any other visible part will turn that part red, indicating that you can click it to establish it as the target part. If you wish to cancel targeting mode, hit the escape key.
Once established, the correct value will be set in the original Part's `target` property and can be used as normal.
The implementation includes several handlers and methods on `PartView` that Halo will call in order to toggle targeting mode. Most of the interaction deals with adding and removing handlers, in particular enter, …

Interactive Targeting v1

---

js/objects/System.js

Our serialization isn't coming out in a pretty print format. Was this on purpose? If it's accidental, then this should change it back to the old way...
This takes care of this issue: https://github.com/UnitedLexCorp/SimpleTalk/issues/214

Write out serialization in pretty print format
